### ISSUE TITLE
Questions about observation time settings

### ISSUE THREAD

**Issue by WWWindrunner** [AllenXuuu/DCR#5]
Thanks for open sourcing your work！
From the code point of view, it seems that you used a longer observation time on the EK100 data set. For example, you used more than 40 frames during training. How to ensure a fair comparison with other work in this case? （RULSTM just use 14 frames）

**Comment by AllenXuuu** [comment]
Hi. Thanks for your interests.
Action anticipation problem like EK100 only requires the same anticipation time $\tau_a=1s$ setting for a fair comparison, but the observation time $\tau_o$ is not restricted, usually specific to a method. For example,  $\tau_o=2s$ in RULSTM, $\tau_o=10s$ in AVT, $\tau_o=60s$ in Ego-OMG. In our work, we follow AVT to set   $\tau_o=10s$ .

**Comment by WWWindrunner** [comment]
Thank you for your reply.

**Comment by WWWindrunner** [comment]
Hello, can you provide a training yaml file of EK100RGBTSN, the accuracy of the default parameter training can not meet the requirements of the paper




风行者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AllenXuuu/DCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月31日(星期六) 中午1:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AllenXuuu/DCR] Questions about observation time settings (Issue #5)





 
Hi. Thanks for your interests.
 Action anticipation problem like EK100 only requires the same anticipation time $\tau_a=1s$ setting for a fair comparison, but the observation time $\tau_o$ is not restricted, usually specific to a method. For example,  $\tau_o=2s$ in RULSTM, $\tau_o=10s$ in AVT, $\tau_o=60s$ in Ego-OMG. In our work, we follow AVT to set   $\tau_o=10s$ .
